name: actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      
      - run: make setup
      # - run: make start
      - name: run tests
        run: make test
      - name: run linter
        run: make lint

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.36ea7e05-ae56-4489-8f20-340ce90b4e08 }}
